apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo
spec:
  selector:
    matchLabels:
      app: argo
  replicas: 2
  template:
    metadata:
      labels:
        app: argo
    spec:
      containers:
      - name: myapp
        image: testcontainers/helloworld
        # ports:
        # - containerPort: 8080
